name: Follett Project -- Hessian Hut
favicon: null
layout_spectrum: 0.19175048545002937
typography_spectrum: 0.17654230119660497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#404429'
    - '#99b53e'
    - '#bdf343'
  brandStrength: 0.8693763299379498
  lightness: 0.7807694773655385
  saturation: 0.37296797102317214
  rhythmicContrast: 0.5992691263090819
purpose: []
